version: '3.8'
services:
    postgres_db:
        image: postgres:latest
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_DB: shop
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin123
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
            - ./init_postgres.sql:/docker-entrypoint-initdb.d/init.sql

    mariadb_db:
        image: mariadb:latest
        container_name: mariadb_db
        restart: always
        environment:
            MYSQL_DATABASE: shop
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin123
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3307:3306'
        volumes:
            - mariadb_data:/var/lib/mysql
            - ./init_mysql.sql:/docker-entrypoint-initdb.d/init.sql

    mysql_db:
        image: mysql:latest
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_DATABASE: shop
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin123
            MYSQL_ROOT_PASSWORD: root
        ports:
            - '3308:3306'
        volumes:
            - mysql_data:/var/lib/mysql
            - ./init_mysql.sql:/docker-entrypoint-initdb.d/init.sql
    mongodb_db:
        image: mongo:latest
        container_name: mongodb_db
        restart: always
        environment:
            MONGO_INITDB_DATABASE: shop
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: admin123
        ports:
            - '27017:27017'
        volumes:
            - mongodb_data:/data/db
    redis:
        image: redis:latest
        container_name: redis
        restart: always
        ports:
            - '6379:6379'
        command:
            [
                'redis-server',
                '--appendonly',
                'yes',
                '--requirepass',
                'supersecret',
            ]
        environment:
            REDIS_PASSWORD: supersecret
        volumes:
            - redis_data:/data
volumes:
    postgres_data:
    mariadb_data:
    mysql_data:
    mongodb_data:
    redis_data:
